openapi: 3.2.0
info:
  title: Griffin Connectivity API
  version: ''
  description: '## Introduction


    The Griffin API is based on REST.'
servers:
- url: https://api.griffin.com/
security:
- api-key-auth: []
tags:
- name: Connectivity
paths:
  /v0/ping:
    get:
      tags:
      - Connectivity
      description: Check your connection to the Griffin API.
      security: []
      responses:
        '204':
          description: No content
      summary: Ping
      operationId: getV0Ping
      x-operation-id-source: derived
components:
  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header
      name: Authorization
      description: 'API token authentication.

        It should follow the format: `GriffinAPIKey g-test-MyKey-XXXXXXX`'
x-tagGroups:
- name: Getting started
  tags:
  - API keys
  - Connectivity
  - Navigation
  - Events
  - Webhooks
  - Message Signatures
- name: Customer verifications
  tags:
  - Legal persons
  - Legal person history
  - Claims
  - Workflows
  - Verifications
  - Decisions
  - Companies House
  - Reliance onboarding
- name: Banking
  tags:
  - Bank accounts
  - Bank account events
  - Bank account restrictions
  - Bank account holds
  - Pooled account membership
  - Payments
  - Transactions
  - Payees
  - Confirmation of payee
  - Open banking
- name: Team management
  tags:
  - Organizations
  - Users
  - Roles
  - Memberships
  - Invitations
x-id:
- default
